flowchart LR
    bread
    vegetable
    meat
    side-dishes
    meal
    subgraph burger-quiz
        burger-factory .-> burger
        meal-factory
    end
    bread -. JOIN-1 .-> burger-factory
    vegetable -. JOIN-2 .-> burger-factory
    meat -. JOIN-3 .-> burger-factory
    burger -. LEFT-JOIN-1 .-> meal-factory
    side-dishes -. LEFT-JOIN-2 .-> meal-factory
    meal-factory .-> meal

style bread fill:pink
style vegetable fill:pink
style meat fill:pink
style side-dishes fill:pink
style burger fill:lightgreen
style meal fill:lightgreen
